apiVersion: v1
kind: Service
metadata:
  name: notinthiscastle-service
spec:
  selector:
    app: notinthiscastle
  ports:
  - protocol: "TCP"
    port: 8080 
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notinthiscastle
spec:
  selector:
    matchLabels:
      app: notinthiscastle
  replicas: 2 
  template:
    metadata:
      labels:
        app: notinthiscastle
    spec:
      containers:
      - name: notinthiscastle
        image: notinthiscastle:latest
        imagePullPolicy: Never 
        ports:
        - containerPort: 5000
